### ISSUE TITLE
Documentation not cleart when not installing via HACS

### ISSUE THREAD

**Issue by Pigi-102** [FrancisLab/hass-climate-scheduler#5]
I'm trying to make this work but installing by hand.
One I've downloaded and copied files to the relvant directory and restarted homeassistant I can't find neither the integration nor the lovelace card.

Would you be so kind to make a better documentatin for those that have no access to HACS ?

Thanks

**Comment by FrancisLab** [comment]
@Pigi-102 copying the files to the relevant directory should be all that is needed to make the custom component available. Can you see any related errors under "Configuration -> Settings -> Logs"? 

The custom component will not appear as an integration in the UI under "Configuration -> Integrations". At the moment, it's only usable through the configuration.yaml file. Supporting UI configuration would require some extra work I believe. Have you tried adding a minimal configuration to configuration.yaml? Something like:

```
switch:
  - platform: climate_scheduler
    name: Test Scheduler
    climate_entities:
      - <THE_CLIMATE_ENTITY_YOU_WANT_TO_CONTROL>
    profiles:
     - id: "Empty Profile"
```

It also will not create a new lovelace card. The UI shown in the documentation is built from a vertical stack card containing a thermostat card and an entities card. The entities card contains the switch & input_select entities generated by the custom entity.  Code for the card looks something like:

```
cards:
  - entity: climate.bedroom
    type: thermostat
  - type: entities
    entities:
      - entity: switch.climate_scheduler_bedroom
      - entity: input_select.bedroom_climate_profile_selector
type: vertical-stack
```
